services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 4001:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - 4002:6379
    volumes:
      - redis_data:/var/lib/redis/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "${GREENLIGHT_APP_DB_DSN}", "up"]
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - web
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["./app", "-db-dsn=${GREENLIGHT_APP_DB_DSN}", "-redis-dsn=${GREENLIGHT_APP_REDIS_DSN}", "-smtp-host=${STMP_HOST}", "-smtp-username=${STMP_USERNAME}", "-smtp-password=${STMP_PASSWORD}"]
    deploy:
      replicas: 2
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  prometheus_data:
  grafana-storage:
  redis_data:

