apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greenlight.fullname" . }}-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation


data:
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  SMTP_HOST: {{ .Values.config.smtpHost | quote }}
  GREENLIGHT_APP_REDIS_DSN: {{ .Values.config.greenlightAppRedisDsn | quote }}