apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "greenlight.fullname" . }}-migrate
  labels:
    {{- include "greenlight.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.migrations.name }}
        image: {{ .Values.migrations.repository }}:{{ .Values.migrations.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        command: ['migrate']
        args: ['-path', '/migrations', '-database', 'postgres://postgres:greenlight@greenlight-db-postgresql:5432/greenlight?sslmode=disable', 'up']
      restartPolicy: Never
  backoffLimit: 4
