apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greenlight.fullname" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  SMTP_USERNAME: {{ .Values.secrets.smtpUsername | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | b64enc | quote }}
