# Default values for greenlight.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: greenlight-app
  pullPolicy: IfNotPresent
  tag: latest

migrations:
  name: greenlight-app-migrations
  repository: greenlight-app-migrate
  pullPolicy: IfNotPresent
  tag: latest
database:
  service_name: greenlight-db-postgresql
redis:
  service_name: greenlight-redis-master

service:
  type: LoadBalancer
  port: 8080
  nodePort: 30140


livenessProbe:
  httpGet:
    path: /v1/healthcheck
    port: http
  initialDelaySeconds: 10
  periodSeconds: 60
readinessProbe:
  httpGet:
    path: /v1/healthcheck
    port: http


config:
  postgresDb: "greenlight"
  smtpHost: "sandbox.smtp.mailtrap.io"
  greenlightAppRedisDsn: "redis://redis:6379"

secrets:
  postgresUser: "postgres"
  postgresPassword: "greenlight"
  smtpUsername: "53aecc97c7ecf7"
  smtpPassword: "ca08463ee04bcd"
